channels:
  - defaults
dependencies:
  - brotlipy=0.7.0
  - ca-certificates=2023.08.22
  - certifi=2023.7.22
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - conda=4.13.0
  - conda-content-trust=0.1.1
  - conda-package-handling=1.7.3
  - cryptography=36.0.0
  - exceptiongroup=1.0.4
  - idna=3.3
  - iniconfig=1.1.1
  - libcxx=12.0.0
  - libffi=3.3
  - ncurses=6.3
  - openssl=1.1.1w
  - packaging=23.1
  - pip=23.3.1
  - pluggy=1.0.0
  - ply=3.11
  - pycosat=0.6.3
  - pycparser=2.21
  - pyopenssl=21.0.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - pytest=7.4.0
  - python=3.9.7
  - python.app=3
  - readline=8.1.2
  - requests=2.27.1
  - ruamel_yaml=0.15.100
  - six=1.16.0
  - sqlite=3.37.0
  - tk=8.6.11
  - tomli=2.0.1
  - tqdm=4.62.3
  - tzdata=2021e
  - urllib3=1.26.7
  - wheel=0.37.1
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
  - pip:
    - annotated-types==0.6.0
    - antlr4-python3-runtime==4.13.1
    - antlr4-tools==0.2
    - anyio==4.3.0
    - distro==1.9.0
    - h11==0.14.0
    - httpcore==1.0.5
    - httpx==0.27.0
    - inflection==0.5.1
    - install-jdk==1.1.0
    - mypy==0.961
    - mypy-extensions==0.4.3
    - nodeenv==1.7.0
    - openai==1.17.0
    - pydantic==2.6.4
    - pydantic-core==2.16.3
    - pyright==1.1.260
    - setuptools==62.3.2
    - sniffio==1.3.1
    - tree-sitter==0.20.0
    - typing-extensions==4.11.0
    - z3-solver==4.12.1.0
