# THIS FILE IS AUTOGENERATED
# CHANGES MAY BE LOST


import ply.lex as lex
    

tokens = (
    r'dis_key',
    r'identifier'
)
    

t_dis_key = r'dis_key'
t_identifier = r'*'
    

def t_newline(t):
    r'\n+'
    t.lexer.lineno += len(t.value)

# A string containing ignored characters (spaces and tabs)
t_ignore  = ' \t'

# Error handling rule
def t_error(t):
    print("Illegal character '%s'" % t.value[0])
    t.lexer.skip(1)

lexer = lex.lex()
    