# THIS FILE IS AUTOGENERATED
# CHANGES MAY BE LOST

from core import meta_system
from typing import TypeVar, Optional
from core.rich_token_system import Grammar, Vocab

D = TypeVar('D')
U = TypeVar('U')




class SemanticsBase(meta_system.Semantics[D,U]):
    pass
    